Environment=prod
env=prod
base.url=https://petstore.swagger.io/v2
base.url2=https://reqres.in
connect.timeout=10000
read.timeout=10000
proxy.enabled=true
proxy.host=127.0.0.1
proxy.port=8888
# Authentication

auth.url=https://dummyjson.com/auth/login
auth.username=emilys
auth.password=emilyspass